# repo-root/mkdocs.yml
site_name: Open Source Marginal Emissions — Docs
theme:
  name: material
plugins:
  - search
  - monorepo
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Weather Data Retrieval: '!include .packages/weather_data_retrieval/mkdocs.yml'
  - Grid Data Retrieval: '!include ./grid_data_retrieval/mkdocs.yml'
  - Data Cleaning and Joining: '!include ./data_cleaning_and_joining/mkdocs.yml'
  - Marginal Emissions Modelling: '!include ./marginal_emissions_modelling/mkdocs.yml'

