# repo-root/mkdocs.yml
site_name: Open Source Marginal Emissions — Docs
site_url: https://YOUR_GH_PAGES_URL_HERE
repo_url: https://github.com/danielkaupa/open-source-marginal-emissions
repo_name: danielkaupa/open-source-marginal-emissions

# Use the repo root as docs so we can reference README.md and information/*
docs_dir: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - autorefs
  - monorepo
  - mkdocstrings:
      handlers:
        python:
          paths:
            - packages/weather_data_retrieval/src
            - packages/grid_data_retrieval/src
            - packages/data_cleaning_and_joining/src
            - packages/marginal_emissions_modelling/src
          options:
            docstring_style: numpy
            show_root_heading: true
            separate_signature: true
            members_order: source
            show_source: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

# Auto-reload when docs edited inside packages or code docstrings
watch:
  - information
  - packages/weather_data_retrieval/docs
  - packages/grid_data_retrieval/docs
  - packages/data_cleaning_and_joining/docs
  - packages/marginal_emissions_modelling/docs
  - packages/weather_data_retrieval/src
  - packages/grid_data_retrieval/src
  - packages/data_cleaning_and_joining/src
  - packages/marginal_emissions_modelling/src

nav:
  - Overview:
      - Introduction to this Repository: README.md
      - Core Concepts and Definitions: information/CORE_CONCEPTS_AND_DEFINITIONS.md
      - Project Roadmap: information/PROJECT_ROADMAP.md
      - Acknowledgements: information/ACKNOWLEDGEMENTS.md

  - Packages:
      - Weather Data Retrieval: '!include ./packages/weather_data_retrieval/mkdocs.yml'
      - Grid Data Retrieval: '!include ./packages/grid_data_retrieval/mkdocs.yml'
      - Data Cleaning and Joining: '!include ./packages/data_cleaning_and_joining/mkdocs.yml'
      - Marginal Emissions Modelling: '!include ./packages/marginal_emissions_modelling/mkdocs.yml'
