[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osme-common"
version = "1.0.0"
description = "Shared helpers for the Open Source Marginal Emissions monorepo."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
include = ["osme_common*"]